# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('ubigeo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ccdd', models.CharField(blank=True, max_length=2, null=True)),
                ('ccpp', models.CharField(blank=True, max_length=2, null=True)),
                ('ccdi', models.CharField(blank=True, max_length=2, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'UBIGEO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('UBIGEO', models.CharField(max_length=6)),
                ('CODCCPP', models.CharField(max_length=4)),
                ('ZONA', models.CharField(max_length=5)),
                ('LLAVE_CCPP', models.CharField(max_length=10)),
                ('LLAVE_ZONA', models.CharField(max_length=15)),
                ('ETIQ_ZONA', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'ZONA',
                'managed': True,
            },
        ),
    ]
