# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'datos_prueba_sms',
                'managed': True,
            },
        ),
    ]
