# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubigeo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id_ambiente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ambiente', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
                'db_table': 'AMBIENTE',
            },
        ),
        migrations.CreateModel(
            name='CargoFuncional',
            fields=[
                ('id_cargofuncional', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_funcionario', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'CARGO_FUNCIONAL',
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id_criterio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_criterio', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_criterio', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'CRITERIO',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('cod_curso', models.CharField(blank=True, max_length=3, null=True)),
                ('nombre_curso', models.CharField(blank=True, max_length=255, null=True)),
                ('nota_minima', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'CURSO',
            },
        ),
        migrations.CreateModel(
            name='CursoCargoFuncional',
            fields=[
                ('id_cursocargofuncional', models.AutoField(primary_key=True, serialize=False)),
                ('id_cargofuncional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.CargoFuncional')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Curso')),
            ],
            options={
                'managed': True,
                'db_table': 'CURSO_CARGO_FUNIONAL',
            },
        ),
        migrations.CreateModel(
            name='CursoCriterio',
            fields=[
                ('cursocriterio', models.AutoField(primary_key=True, serialize=False)),
                ('ponderacion', models.IntegerField()),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Criterio')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Curso')),
            ],
            options={
                'db_table': 'CURSO_CRITERIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DirectorioLocal',
            fields=[
                ('id_local', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_local', models.CharField(blank=True, max_length=300, null=True)),
                ('zona_ubicacion_local', models.CharField(blank=True, db_column='zona_ubicacion_local', max_length=5, null=True)),
                ('tipo_via', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre_via', models.CharField(blank=True, max_length=300, null=True)),
                ('referencia', models.CharField(blank=True, max_length=300, null=True)),
                ('n_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('km_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('mz_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('lote_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('piso_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono_local_fijo', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_local_celular', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('turno_uso_local', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad_local_total', models.IntegerField(blank=True, null=True)),
                ('capacidad_local_usar', models.IntegerField(blank=True, null=True)),
                ('funcionario_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_email', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_email', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_total_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_otros', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_otros', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_otros', models.IntegerField(blank=True, null=True)),
                ('especifique_otros', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_total_computo', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_computo', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_computo', models.IntegerField(blank=True, null=True)),
                ('ubigeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Ubigeo')),
            ],
            options={
                'managed': True,
                'db_table': 'DIRECTORIOLOCAL',
            },
        ),
        migrations.CreateModel(
            name='DirectorioLocalAmbiente',
            fields=[
                ('id_localambiente', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('n_piso', models.IntegerField(blank=True, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('id_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Ambiente')),
            ],
            options={
                'managed': True,
                'db_table': 'DIRECTORIOLOCAL_AMBIENTE',
            },
        ),
        migrations.CreateModel(
            name='DirectorioLocalCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambientes', models.ManyToManyField(through='locales_consecucion.DirectorioLocalAmbiente', to='locales_consecucion.Ambiente')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Curso')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.DirectorioLocal')),
            ],
            options={
                'db_table': 'DIRECTORIOLOCAL_CURSO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id_etapa', models.AutoField(primary_key=True, serialize=False)),
                ('cod_etapa', models.CharField(blank=True, max_length=3, null=True)),
                ('nombre_etapa', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'ETAPA',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id_local', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_local', models.CharField(blank=True, max_length=300, null=True)),
                ('zona_ubicacion_local', models.CharField(blank=True, db_column='zona_ubicacion_local', max_length=5, null=True)),
                ('tipo_via', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre_via', models.CharField(blank=True, max_length=300, null=True)),
                ('referencia', models.CharField(blank=True, max_length=300, null=True)),
                ('n_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('km_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('mz_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('lote_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('piso_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono_local_fijo', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_local_celular', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('turno_uso_local', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad_local_total', models.IntegerField(blank=True, null=True)),
                ('capacidad_local_usar', models.IntegerField(blank=True, null=True)),
                ('funcionario_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_email', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_email', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_total_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_otros', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_otros', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_otros', models.IntegerField(blank=True, null=True)),
                ('especifique_otros', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_total_computo', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_computo', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_computo', models.IntegerField(blank=True, null=True)),
                ('id_directoriolocal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.DirectorioLocal')),
                ('ubigeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Ubigeo')),
            ],
            options={
                'managed': True,
                'db_table': 'LOCAL',
            },
        ),
        migrations.CreateModel(
            name='LocalAmbiente',
            fields=[
                ('id_localambiente', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('n_piso', models.IntegerField(blank=True, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('id_instructor', models.IntegerField(blank=True, null=True)),
                ('id_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Ambiente')),
            ],
            options={
                'managed': True,
                'db_table': 'LOCAL_AMBIENTE',
            },
        ),
        migrations.CreateModel(
            name='LocalAmbito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccdd', models.CharField(blank=True, max_length=2, null=True)),
                ('ccpp', models.CharField(blank=True, max_length=2, null=True)),
                ('ccdi', models.CharField(blank=True, max_length=2, null=True)),
                ('zona', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'LocalAmbito',
            },
        ),
        migrations.CreateModel(
            name='LocalCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambientes', models.ManyToManyField(through='locales_consecucion.LocalAmbiente', to='locales_consecucion.Ambiente')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Curso')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Local')),
            ],
            options={
                'db_table': 'LOCAL_CURSO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_pea', models.AutoField(primary_key=True, serialize=False)),
                ('id_per', models.CharField(blank=True, max_length=8, null=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('ape_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('ape_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=100, null=True)),
                ('id_convocatoriacargo', models.CharField(blank=True, max_length=4, null=True)),
                ('zona', models.CharField(blank=True, max_length=5, null=True)),
                ('contingencia', models.IntegerField(blank=True, null=True)),
                ('baja_estado', models.IntegerField(blank=True, default=0, null=True)),
                ('alta_estado', models.IntegerField(blank=True, default=0, null=True)),
                ('id_cargofuncional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.CargoFuncional')),
                ('id_pea_reemplazo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Personal')),
                ('ubigeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Ubigeo')),
            ],
            options={
                'managed': True,
                'db_table': 'PERSONAL',
            },
        ),
        migrations.CreateModel(
            name='PersonalAula',
            fields=[
                ('id_peaaula', models.AutoField(primary_key=True, serialize=False)),
                ('id_localambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.LocalAmbiente')),
                ('id_pea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Personal')),
            ],
            options={
                'managed': True,
                'db_table': 'PersonalAula',
            },
        ),
        migrations.CreateModel(
            name='PersonalAulaAsistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno_manana', models.IntegerField(blank=True, null=True)),
                ('turno_tarde', models.IntegerField(blank=True, null=True)),
                ('fecha', models.CharField(max_length=50)),
                ('peaaula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalaula', to='locales_consecucion.PersonalAula')),
            ],
            options={
                'managed': True,
                'db_table': 'PersonalAulaAsistencia',
            },
        ),
        migrations.CreateModel(
            name='PersonalAulaNotaFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.FloatField()),
            ],
            options={
                'managed': True,
                'db_table': 'PersonalAulaNotaFinal',
            },
        ),
        migrations.CreateModel(
            name='PersonalCursoCriterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(blank=True, null=True)),
                ('cursocriterio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.CursoCriterio')),
                ('peaaula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalaula_notas', to='locales_consecucion.PersonalAula')),
            ],
            options={
                'managed': True,
                'db_table': 'PeaCursoCriterio',
            },
        ),
        migrations.CreateModel(
            name='TipoResultadosCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'managed': True,
                'db_table': 'TipoResultadoCapacitacion',
            },
        ),
        migrations.CreateModel(
            name='UbigeoCursoMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.IntegerField()),
                ('ubigeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Ubigeo')),
            ],
        ),
        migrations.AddField(
            model_name='personalaulanotafinal',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.TipoResultadosCapacitacion'),
        ),
        migrations.AddField(
            model_name='personalaulanotafinal',
            name='peaaula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalaula_notafinal', to='locales_consecucion.PersonalAula'),
        ),
        migrations.AddField(
            model_name='localambito',
            name='localcurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localescurso', to='locales_consecucion.LocalCurso'),
        ),
        migrations.AddField(
            model_name='localambiente',
            name='localcurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.LocalCurso'),
        ),
        migrations.AddField(
            model_name='localambiente',
            name='pea',
            field=models.ManyToManyField(through='locales_consecucion.PersonalAula', to='locales_consecucion.Personal'),
        ),
        migrations.AddField(
            model_name='directoriolocalambiente',
            name='localcurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.DirectorioLocalCurso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='criterios',
            field=models.ManyToManyField(through='locales_consecucion.CursoCriterio', to='locales_consecucion.Criterio'),
        ),
        migrations.AddField(
            model_name='curso',
            name='directoriolocales',
            field=models.ManyToManyField(through='locales_consecucion.DirectorioLocalCurso', to='locales_consecucion.DirectorioLocal'),
        ),
        migrations.AddField(
            model_name='curso',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Etapa'),
        ),
        migrations.AddField(
            model_name='curso',
            name='locales',
            field=models.ManyToManyField(through='locales_consecucion.LocalCurso', to='locales_consecucion.Local'),
        ),
        migrations.AlterUniqueTogether(
            name='localcurso',
            unique_together=set([('local', 'curso')]),
        ),
        migrations.AlterUniqueTogether(
            name='directoriolocalcurso',
            unique_together=set([('local', 'curso')]),
        ),
        migrations.AlterUniqueTogether(
            name='cursocriterio',
            unique_together=set([('curso', 'cursocriterio')]),
        ),
    ]
