# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeaNotaFinalSinInternet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.FloatField()),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.TipoResultadosCapacitacion')),
                ('pea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_notafinal', to='locales_consecucion.Personal')),
            ],
            options={
                'db_table': 'PERSONALNOTAFINAL_SININTERNET',
                'managed': True,
            },
        ),
    ]
