# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Curso')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Local')),
            ],
            options={
                'managed': True,
                'db_table': 'LOCAL_CURSO',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='locales',
            field=models.ManyToManyField(through='locales_consecucion.LocalCurso', to='locales_consecucion.Local'),
        ),
        migrations.AlterUniqueTogether(
            name='localcurso',
            unique_together=set([('local', 'curso')]),
        ),
    ]
