# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesionPersonal',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('detalle', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'PROFESION_PERSONAL',
            },
        ),
        migrations.AlterField(
            model_name='personal',
            name='profesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.ProfesionPersonal'),
        ),
        migrations.DeleteModel(
            name='Profesion',
        ),
    ]
