# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metacapacitacionpersonal',
            name='zona',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
