# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0002_auto_20170523_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localambiente',
            name='capacidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
