# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0002_auto_20170409_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='profesion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.ProfesionPersonal'),
        ),
    ]
