# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0002_auto_20170303_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='zona_ubicacion_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Zona'),
        ),
    ]
