# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0002_peanotafinalsininternet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peanotafinalsininternet',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='personalaulanotafinal',
            name='estado',
        ),
        migrations.AddField(
            model_name='peanotafinalsininternet',
            name='bandaprob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peanotafinalsininternet',
            name='capacita',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peanotafinalsininternet',
            name='seleccionado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peanotafinalsininternet',
            name='sw_titu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalaulanotafinal',
            name='bandaprob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalaulanotafinal',
            name='capacita',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalaulanotafinal',
            name='seleccionado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalaulanotafinal',
            name='sw_titu',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
