# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0002_auto_20170410_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
