# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0003_auto_20170329_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='peanotafinalsininternet',
            name='notacap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalaulanotafinal',
            name='notacap',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
