# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0003_auto_20170523_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoriolocal',
            name='gestion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='directoriolocal',
            name='manzana',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='directoriolocal',
            name='numero_alumnos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='directoriolocal',
            name='numero_docentes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='directoriolocal',
            name='numero_secciones',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
