# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0001_initial'),
        ('locales_consecucion', '0003_auto_20170303_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorioLocal',
            fields=[
                ('id_local', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_local', models.CharField(blank=True, max_length=300, null=True)),
                ('tipo_via', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre_via', models.CharField(blank=True, max_length=300, null=True)),
                ('referencia', models.CharField(blank=True, max_length=300, null=True)),
                ('n_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('km_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('mz_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('lote_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('piso_direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono_local_fijo', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_local_celular', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('turno_uso_local', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad_local_total', models.IntegerField(blank=True, null=True)),
                ('capacidad_local_usar', models.IntegerField(blank=True, null=True)),
                ('funcionario_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_email', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionario_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_email', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_celular', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_total_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_aulas', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_auditorios', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_sala', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_oficina', models.IntegerField(blank=True, null=True)),
                ('cantidad_total_otros', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_otros', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_otros', models.IntegerField(blank=True, null=True)),
                ('especifique_otros', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_total_computo', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible_computo', models.IntegerField(blank=True, null=True)),
                ('cantidad_usar_computo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DIRECTORIOLOCAL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DirectorioLocalAmbiente',
            fields=[
                ('id_localambiente', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('n_piso', models.IntegerField(blank=True, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('id_ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Ambiente')),
                ('id_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.DirectorioLocal')),
            ],
            options={
                'db_table': 'DIRECTORIOLOCAL_AMBIENTE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DirectorioLocalCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Curso')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.DirectorioLocal')),
            ],
            options={
                'db_table': 'DIRECTORIOLOCAL_CURSO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LocalZonas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localcurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.LocalCurso')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Zona')),
            ],
            options={
                'db_table': 'LOCALZONAS',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='directoriolocal',
            name='ambientes',
            field=models.ManyToManyField(through='locales_consecucion.DirectorioLocalAmbiente', to='locales_consecucion.Ambiente'),
        ),
        migrations.AddField(
            model_name='directoriolocal',
            name='ubigeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Ubigeo'),
        ),
        migrations.AddField(
            model_name='directoriolocal',
            name='zona_ubicacion_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Zona'),
        ),
        migrations.AddField(
            model_name='localcurso',
            name='zonas',
            field=models.ManyToManyField(through='locales_consecucion.LocalZonas', to='ubigeo.Zona'),
        ),
        migrations.AlterUniqueTogether(
            name='localzonas',
            unique_together=set([('localcurso', 'zona')]),
        ),
        migrations.AlterUniqueTogether(
            name='directoriolocalcurso',
            unique_together=set([('local', 'curso')]),
        ),
    ]
