# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0001_initial'),
        ('locales_consecucion', '0004_auto_20170309_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoFuncional',
            fields=[
                ('id_cargofuncional', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_funcionario', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'CARGO_FUNCIONAL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CursoCargoFuncional',
            fields=[
                ('id_cursocargofuncional', models.AutoField(primary_key=True, serialize=False)),
                ('id_cargofuncional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.CargoFuncional')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Curso')),
            ],
            options={
                'db_table': 'CURSO_CARGO_FUNIONAL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_pea', models.AutoField(primary_key=True, serialize=False)),
                ('id_per', models.CharField(blank=True, max_length=8, null=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('ape_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('ape_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('id_convocatoriacargo', models.CharField(blank=True, max_length=4, null=True)),
                ('contingencia', models.IntegerField(blank=True, null=True)),
                ('baja_estado', models.IntegerField(blank=True, default=0, null=True)),
                ('alta_estado', models.IntegerField(blank=True, default=0, null=True)),
                ('id_cargofuncional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.CargoFuncional')),
                ('ubigeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Ubigeo')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Zona')),
            ],
            options={
                'db_table': 'PERSONAL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonalAula',
            fields=[
                ('id_peaaula', models.AutoField(primary_key=True, serialize=False)),
                ('pea_fecha', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'PersonalAula',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='directoriolocal',
            name='ambientes',
        ),
        migrations.RemoveField(
            model_name='directoriolocalambiente',
            name='id_local',
        ),
        migrations.RemoveField(
            model_name='local',
            name='ambientes',
        ),
        migrations.RemoveField(
            model_name='localambiente',
            name='id_local',
        ),
        migrations.AddField(
            model_name='directoriolocalambiente',
            name='localcurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.DirectorioLocalCurso'),
        ),
        migrations.AddField(
            model_name='directoriolocalcurso',
            name='ambientes',
            field=models.ManyToManyField(through='locales_consecucion.DirectorioLocalAmbiente', to='locales_consecucion.Ambiente'),
        ),
        migrations.AddField(
            model_name='localambiente',
            name='localcurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.LocalCurso'),
        ),
        migrations.AddField(
            model_name='localcurso',
            name='ambientes',
            field=models.ManyToManyField(through='locales_consecucion.LocalAmbiente', to='locales_consecucion.Ambiente'),
        ),
        migrations.AddField(
            model_name='personalaula',
            name='id_localambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.LocalAmbiente'),
        ),
        migrations.AddField(
            model_name='personalaula',
            name='id_pea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Personal'),
        ),
    ]
