# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0004_auto_20170410_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
