# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0004_auto_20170529_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoriolocal',
            name='ccdd',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='directoriolocal',
            name='ccdi',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='directoriolocal',
            name='ccpp',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='ccdd',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='ccdi',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='ccpp',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='ccdd',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='ccdi',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='ccpp',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
