# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0004_auto_20170329_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='GISLimiteDep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CCDD', models.CharField(max_length=2)),
                ('CAPACITACION_CURSO1', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO2', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO3', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO4', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO5', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO6', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO7', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO8', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO9', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO10', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO11', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO12', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO14', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO15', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO16', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO17', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sde.CPV_SEGMENTACION_DBO_TB_LIMITE_DEP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GISLimiteDis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CCDD', models.CharField(max_length=2)),
                ('CCPP', models.CharField(max_length=2)),
                ('CCDI', models.CharField(max_length=2)),
                ('UBIGEO', models.CharField(max_length=6)),
                ('CAPACITACION_CURSO1', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO2', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO3', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO4', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO5', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO6', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO7', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO8', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO9', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO10', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO11', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO12', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO14', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO15', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO16', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO17', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sde.CPV_SEGMENTACION_DBO_TB_LIMITE_DIS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GISLimiteProv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CCDD', models.CharField(max_length=2)),
                ('CCPP', models.CharField(max_length=2)),
                ('CAPACITACION_CURSO1', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO2', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO3', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO4', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO5', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO6', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO7', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO8', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO9', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO10', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO11', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO12', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO14', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO15', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO16', models.IntegerField(blank=True, null=True)),
                ('CAPACITACION_CURSO17', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sde.CPV_SEGMENTACION_DBO_TB_LIMITE_PRO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetaAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccdd', models.CharField(max_length=2)),
                ('ccpp', models.CharField(max_length=2)),
                ('ccdi', models.CharField(max_length=2)),
                ('ubigeo', models.CharField(max_length=6)),
                ('curso', models.IntegerField()),
            ],
            options={
                'db_table': 'META_AULA',
                'managed': True,
            },
        ),
    ]
