# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0005_auto_20170410_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='edad',
        ),
    ]
