# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0005_auto_20170309_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoriolocal',
            name='zona_ubicacion_local',
            field=models.CharField(blank=True, db_column='zona_ubicacion_local', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='zona_ubicacion_local',
            field=models.CharField(blank=True, db_column='zona_ubicacion_local', max_length=5, null=True),
        ),
    ]
