# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0005_gislimitedep_gislimitedis_gislimiteprov_metaaula'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='total_aulas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='gislimitedep',
            table='sde].[CPV_SEGMENTACION_DBO_TB_LIMITE_DEP',
        ),
    ]
