# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0006_auto_20170310_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='directoriolocales',
            field=models.ManyToManyField(through='locales_consecucion.DirectorioLocalCurso', to='locales_consecucion.DirectorioLocal'),
        ),
    ]
