# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0006_auto_20170406_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaaula',
            name='meta',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='gislimitedis',
            table='sde].[CPV_SEGMENTACION_DBO_TB_LIMITE_DIS',
        ),
        migrations.AlterModelTable(
            name='gislimiteprov',
            table='sde].[CPV_SEGMENTACION_DBO_TB_LIMITE_PRO',
        ),
    ]
