# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0006_remove_personal_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
