# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0007_curso_directoriolocales'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='id_directoriolocal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.DirectorioLocal'),
        ),
    ]
