# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0007_personal_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metacapacitacionpersonal',
            name='zona',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
