# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0008_auto_20170412_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='usar',
            field=models.IntegerField(default=0),
        ),
    ]
