# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0008_local_id_directoriolocal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAulaAsistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno_manana', models.IntegerField(blank=True, null=True)),
                ('turno_tarde', models.IntegerField(blank=True, null=True)),
                ('fecha', models.CharField(max_length=50)),
            ],
            options={
                'managed': True,
                'db_table': 'PersonalAulaAsistencia',
            },
        ),
        migrations.RemoveField(
            model_name='personalaula',
            name='pea_fecha',
        ),
        migrations.AddField(
            model_name='personalaula',
            name='id_instructor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='zona',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='personalaulaasistencia',
            name='peaaula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.PersonalAula'),
        ),
    ]
