# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0009_auto_20170312_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='localambiente',
            name='pea',
            field=models.ManyToManyField(through='locales_consecucion.PersonalAula', to='locales_consecucion.Personal'),
        ),
    ]
