# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0009_local_usar'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='total_disponibles',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
