# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0010_localambiente_pea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalaula',
            name='id_instructor',
        ),
        migrations.AddField(
            model_name='localambiente',
            name='id_instructor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
