# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0010_local_total_disponibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoriolocal',
            name='total_aulas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directoriolocal',
            name='total_disponibles',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
