# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0011_auto_20170313_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaulaasistencia',
            name='peaaula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalaula', to='locales_consecucion.PersonalAula'),
        ),
    ]
