# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0011_auto_20170504_1502'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cursocargofuncional',
            unique_together=set([('id_cargofuncional', 'id_curso')]),
        ),
    ]
