# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0015_auto_20170316_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalcursocriterio',
            name='criterio',
        ),
        migrations.AddField(
            model_name='personalcursocriterio',
            name='cursocriterio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.CursoCriterio'),
        ),
    ]
