# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0016_auto_20170316_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre_curso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
