# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0018_auto_20170317_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaulanotafinal',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.TipoResultadosCapacitacion'),
        ),
    ]
