# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0019_auto_20170317_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='localzonas',
            name='ubigeo',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='localzonas',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Zona'),
        ),
    ]
