# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0020_auto_20170319_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localzonas',
            name='ubigeo',
        ),
        migrations.AddField(
            model_name='localzonas',
            name='ccdd',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='localzonas',
            name='ccdi',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='localzonas',
            name='ccpp',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
