# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0021_auto_20170320_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAmbito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccdd', models.CharField(blank=True, max_length=2, null=True)),
                ('ccpp', models.CharField(blank=True, max_length=2, null=True)),
                ('ccdi', models.CharField(blank=True, max_length=2, null=True)),
                ('zona', models.CharField(max_length=5, null=True)),
            ],
            options={
                'db_table': 'LocalAmbito',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='localzonas',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='localzonas',
            name='localcurso',
        ),
        migrations.RemoveField(
            model_name='localzonas',
            name='zona',
        ),
        migrations.RemoveField(
            model_name='localcurso',
            name='zonas',
        ),
        migrations.DeleteModel(
            name='LocalZonas',
        ),
        migrations.AddField(
            model_name='localambito',
            name='localcurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localescurso', to='locales_consecucion.LocalCurso'),
        ),
    ]
