# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0022_auto_20170321_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localambito',
            name='zona',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
