# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0023_auto_20170323_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='id_cargofuncional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.CargoFuncional'),
        ),
    ]
