# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0001_initial'),
        ('locales_consecucion', '0024_auto_20170323_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbigeoCursoMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.IntegerField()),
                ('ubigeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Ubigeo')),
            ],
        ),
    ]
