# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0025_ubigeocursometa'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='celular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
