# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha177',
            fields=[
                ('id_per', models.IntegerField(primary_key=True, serialize=False)),
                ('id_convocatoriacargo', models.IntegerField()),
                ('capacita', models.IntegerField()),
                ('notacap', models.FloatField()),
                ('seleccionado', models.IntegerField()),
                ('sw_titu', models.IntegerField()),
                ('bandaprob', models.IntegerField()),
            ],
            options={
                'db_table': 'ficha_177',
                'managed': False,
            },
        ),
    ]
