# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20170328_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
