# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_reportes_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
