# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_reportes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='template_html',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
