# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_reportes_template_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='template_html',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
