# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0006_auto_20170403_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='url_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
