# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0008_reportes_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='campos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
