# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0009_reportes_campos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscritos',
            fields=[
                ('id_per', models.IntegerField(primary_key=True, serialize=False)),
                ('id_cargofuncional', models.IntegerField()),
                ('ccdd_i', models.CharField(max_length=2)),
                ('ccpp_i', models.CharField(max_length=2)),
                ('ccdi_i', models.CharField(max_length=2)),
            ],
            options={
                'managed': False,
                'db_table': 'v_inscritos_censos',
            },
        ),
    ]
