# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locales_consecucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolCursoModulosSeguridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=10)),
                ('modulo', models.CharField(max_length=20)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Curso')),
            ],
            options={
                'db_table': 'ROLCURSOMODULOSSEGURIDAD',
                'managed': True,
            },
        ),
    ]
