# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locales_consecucion', '0011_auto_20170504_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.IntegerField()),
                ('rol', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Curso')),
            ],
            options={
                'managed': True,
                'db_table': 'MENUROLCURSO',
            },
        ),
    ]
