# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0011_auto_20170504_1502'),
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRolModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.IntegerField()),
            ],
            options={
                'db_table': 'ROLCURSOMODULO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RolCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Curso')),
            ],
            options={
                'db_table': 'ROLCURSO',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='menurol',
            name='curso',
        ),
        migrations.DeleteModel(
            name='MenuRol',
        ),
        migrations.AddField(
            model_name='menurolmodulo',
            name='rolcurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.RolCurso'),
        ),
    ]
