# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0003_auto_20170523_1616'),
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Curso')),
            ],
            options={
                'managed': True,
                'db_table': 'ROLCURSOS',
            },
        ),
        migrations.CreateModel(
            name='RolCursoModulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=20)),
                ('rolcurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.RolCurso')),
            ],
            options={
                'managed': True,
                'db_table': 'ROLCURSOS_MODULOS',
            },
        ),
    ]
