# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_rolcurso_rolcursomodulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolcursomodulos',
            name='visualiza',
            field=models.IntegerField(default=1),
        ),
    ]
