# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0001_initial'),
        ('controlcalidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioLocales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.LocalCurso')),
            ],
            options={
                'db_table': 'USUARIO_LOCALES',
                'managed': True,
            },
        ),
    ]
