# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlcalidad', '0002_usuariolocales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariolocales',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Local'),
        ),
    ]
