# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0005_auto_20170531_1140'),
        ('controlcalidad', '0004_auto_20170524_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Curso')),
            ],
            options={
                'managed': True,
                'db_table': 'MANUAL',
            },
        ),
        migrations.CreateModel(
            name='RespuestaAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave', models.IntegerField(blank=True, null=True)),
                ('pregunta', models.IntegerField(blank=True, null=True)),
                ('respuesta_texto', models.CharField(blank=True, max_length=255, null=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Local')),
                ('opcionselected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlcalidad.Opciones')),
            ],
            options={
                'managed': True,
                'db_table': 'RESPUESTAAULA',
            },
        ),
        migrations.CreateModel(
            name='RespuestaLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave', models.IntegerField(blank=True, null=True)),
                ('pregunta', models.IntegerField(blank=True, null=True)),
                ('opcional', models.CharField(blank=True, max_length=255, null=True)),
                ('respuesta_texto', models.CharField(blank=True, max_length=255, null=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Local')),
                ('opcionselected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlcalidad.Opciones')),
            ],
            options={
                'managed': True,
                'db_table': 'RESPUESTALOCAL',
            },
        ),
        migrations.CreateModel(
            name='RespuestaManuales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave', models.IntegerField(blank=True, null=True)),
                ('pregunta', models.IntegerField(blank=True, null=True)),
                ('respuesta_texto', models.CharField(blank=True, max_length=255, null=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Local')),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlcalidad.Manual')),
                ('opcionselected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlcalidad.Opciones')),
            ],
            options={
                'managed': True,
                'db_table': 'RESPUESTAMANUALES',
            },
        ),
        migrations.CreateModel(
            name='TipoFormato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'managed': True,
                'db_table': 'TIPO_FORMATO',
            },
        ),
        migrations.RenameField(
            model_name='grupopreguntas',
            old_name='titulo2',
            new_name='conjunto',
        ),
        migrations.RenameField(
            model_name='preguntas',
            old_name='order',
            new_name='conjunto',
        ),
        migrations.RemoveField(
            model_name='formatos',
            name='curso',
        ),
        migrations.AddField(
            model_name='formatos',
            name='tipo_formato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controlcalidad.TipoPregunta'),
        ),
        migrations.AddField(
            model_name='grupopreguntas',
            name='tipo_titulo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='formatos',
            name='manual_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controlcalidad.Manual'),
        ),
    ]
