# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0005_auto_20170531_1140'),
        ('controlcalidad', '0005_auto_20170612_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='AulaInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.IntegerField(blank=True, null=True)),
                ('instructor', models.IntegerField(blank=True, null=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Local')),
            ],
            options={
                'db_table': 'AULAINSTRUCTOR',
                'managed': True,
            },
        ),
    ]
