# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlcalidad', '0011_respuestalocal_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaaula',
            name='curso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuestamanuales',
            name='curso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
