# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlcalidad', '0012_auto_20170615_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'CAPITULOS',
            },
        ),
        migrations.CreateModel(
            name='CapitulosManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlcalidad.Capitulos')),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlcalidad.Manual')),
            ],
            options={
                'managed': True,
                'db_table': 'CAPITULOSMANUAL',
            },
        ),
    ]
