# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlcalidad', '0013_capitulos_capitulosmanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestamanuales',
            name='cantidaddocumentos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
