# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales_consecucion', '0005_auto_20170531_1140'),
        ('controlcalidad', '0014_respuestamanuales_cantidaddocumentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuetaDuranteManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.IntegerField(blank=True, null=True)),
                ('aula', models.IntegerField(blank=True, null=True)),
                ('fecha', models.CharField(blank=True, max_length=255, null=True)),
                ('pregunta', models.IntegerField(blank=True, null=True)),
                ('respuesta1', models.IntegerField(blank=True, null=True)),
                ('respuesta2', models.IntegerField(blank=True, null=True)),
                ('respuesta3', models.IntegerField(blank=True, null=True)),
                ('respuesta4', models.IntegerField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales_consecucion.Curso')),
            ],
            options={
                'managed': True,
                'db_table': 'RESPUESTADURANTEMANUAL',
            },
        ),
    ]
