# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlcalidad', '0015_respuetadurantemanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuetadurantemanual',
            name='llave',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
