# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlcalidad', '0021_auto_20170620_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuetadurantemanual',
            name='respuesta1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='respuetadurantemanual',
            name='respuesta2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='respuetadurantemanual',
            name='respuesta3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='respuetadurantemanual',
            name='respuesta4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
