# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlcalidad', '0025_respuestaaula_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestamanuales',
            name='cantidaddodefectuosos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
