# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlcalidad', '0007_respuestaaula_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestamanuales',
            name='cantidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='respuestamanuales',
            name='opcional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
