# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlcalidad', '0009_manual_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaaula',
            name='local',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
