# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlcalidad', '0010_respuestaaula_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestalocal',
            name='curso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
