# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlcalidad', '0016_respuetadurantemanual_llave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuetadurantemanual',
            name='curso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
