# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlcalidad', '0017_auto_20170619_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuetadurantemanual',
            name='manual',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
