# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlcalidad', '0019_respuestadurantecapitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestadurantecapitulo',
            name='respuesta10',
        ),
        migrations.RemoveField(
            model_name='respuestadurantecapitulo',
            name='respuesta11',
        ),
        migrations.RemoveField(
            model_name='respuestadurantecapitulo',
            name='respuesta3',
        ),
        migrations.RemoveField(
            model_name='respuestadurantecapitulo',
            name='respuesta4',
        ),
        migrations.RemoveField(
            model_name='respuestadurantecapitulo',
            name='respuesta5',
        ),
        migrations.RemoveField(
            model_name='respuestadurantecapitulo',
            name='respuesta6',
        ),
        migrations.RemoveField(
            model_name='respuestadurantecapitulo',
            name='respuesta7',
        ),
        migrations.RemoveField(
            model_name='respuestadurantecapitulo',
            name='respuesta8',
        ),
        migrations.RemoveField(
            model_name='respuestadurantecapitulo',
            name='respuesta9',
        ),
    ]
