# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlcalidad', '0022_auto_20170620_1441'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RespuetaDuranteManual',
            new_name='RespuestaDuranteManual',
        ),
    ]
