# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlcalidad', '0023_auto_20170620_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestalocal',
            name='instructor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
