# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccdd', models.CharField(max_length=2)),
                ('ccpp', models.CharField(max_length=2)),
                ('ccdi', models.CharField(max_length=2)),
                ('ubigeo', models.CharField(max_length=6)),
                ('curso', models.IntegerField()),
                ('observacion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'OBSERVACION_CURSO',
                'managed': True,
            },
        ),
    ]
